### ISSUE TITLE
TypeError: XRegExp is not a function on atom 1.6.2

### ISSUE THREAD

**Issue by dotboris** [AtomLinter/linter-clojure#37]
I get the following exception in atom 1.6.2 on linux. I just installed it and have nothing configured.

```
TypeError: XRegExp is not a function
    at Object.parse (/home/boris/.atom/packages/linter-rubocop/node_modules/atom-linter/lib/helpers.js:424:18)
    at /home/boris/.atom/packages/linter-clojure/lib/init.coffee:31:20
    at /home/boris/.atom/packages/linter-clojure/lib/init.coffee:31:20
```

**Comment by Arcanemagus** [comment]
Looks like Atom decided to use a helper library that this requires from `linter-rubocop`, that seems to be _very_ out of date. Can you try re-installing `linter-rubocop` and restarting Atom?

**Comment by dotboris** [comment]
I uninstalled and reinstalled `linter-rubocop`.

When I uninstalled it, the issue was gone. It came back as soon as I reinstalled it.

**Comment by Arcanemagus** [comment]
That is... bizarre. Do you have Node.js installed on your system? If so can you run `npm list --depth=1` in both the `linter-rubocop` and `linter-clojure` directories?

**Comment by dotboris** [comment]
Here you go. Hope that helps.

```
➜  ~  cd .atom/packages/
➜  packages  cd linter-rubocop
➜  linter-rubocop  npm list --depth=1
linter-rubocop@0.4.7 /home/boris/.atom/packages/linter-rubocop
`-- atom-linter@4.3.0
  +-- consistent-path@1.1.1
  +-- tmp@0.0.28 invalid
  `-- xregexp@3.1.0

npm ERR! invalid: tmp@0.0.28 /home/boris/.atom/packages/linter-rubocop/node_modules/atom-linter/node_modules/tmp
➜  linter-rubocop  cd ../linter-clojure
➜  linter-clojure  npm list --depth=1
linter-clojure@1.1.2 /home/boris/.atom/packages/linter-clojure
+-- atom-linter@4.6.1
| +-- consistent-env@1.1.2
| +-- named-js-regexp@1.3.1
| +-- sb-promisify@1.3.0
| `-- tmp@0.0.28
`-- atom-package-deps@3.0.9
  `-- atom-package-path@1.1.0
```

**Comment by wesbaker** [comment]
I'm having similar issues, here's what I get:

**Comment by wesbaker** [comment]
I managed to fix it, but I'm unsure of the implications:

1. `cd ~/.atom/packages/linter-rubocop`
2. Open `package.json` and replace *all* instances of `4.3.0` with `4.7.0`
3. `rm -rf node_modules`
4. `npm install`
5. Restart Atom

**Comment by Arcanemagus** [comment]
Marking this as closed since this is a bizarre bug in APM at worst, and far more likely just a random fluke.
