### ISSUE TITLE
Empty stderr throws and error and blocks linter's code-checking pipe

### ISSUE THREAD

**Issue by ehteqx** [AtomLinter/linter-clojure#56]
### Description
The problem seems to affect the linter only when used with linter-clojure (or other JVM-based languages linters). When no error is detected by the linter (thus leading to an empty stderr), an "Unknown error. The process terminated with no output. Error code: 0" message is shown [1] in Developers Tools Console and from now on the linter stops working until an error in the code is detected [2], and stderr populated. If, afterwards, no error is present in the code and the linter is triggered, still the linter shows the last non-empty stderr content [3]. The linter's functionality is therefore disrupted.

**Reproducibility**: 100%

### Steps to reproduce
After the linter is installed...
1. Open (or create new file, then save it) a .clj file with obviously bugless code in it, i.e.:
```
(+ 1 2 3)
```
2. Save it, so as to trigger the linting process. Case [1] ensues.
3. Add code with errors i.e.:
```
(+ 1 2 3)
xyz
```
4. Save it, so as to trigger the linting process. An error at line 2 is detected "Cannot resolve xyz", but the linter itself works properly (case [2]).
5. Remove the buggy line:
```
(+ 1 2 3)
xyz
```
6. Save it, so as to trigger the linting process. Still, an error at line 2 is detected "Cannot resolve xyz", the the linter itself works properly but there's not even a line 2 (case [3]).

### Suggested fix
See pull #55

### Versions
**OS** : Ubuntu 16.04, fully updated
**Atom install method** : Official DEB package from https://atom.io/
**AtomLinter and linter-clojure install method** : From inside Atom, Packages section
**linter version** : 2.2.0 (steelbrain)
**linter-clojure version** : 1.1.3 

* Output of <code>atom --version</code> : 
```
Atom    : 1.19.3
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

* Output of <code>apm --version</code> : 
```
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.14.1
```

**Comment by Arcanemagus** [comment]
Fixed by #55.
